/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V5RouteImport } from './routes/v5'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FlowStatesRouteImport } from './routes/flow-states'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V4IndexRouteImport } from './routes/v4.index'
import { Route as V3IndexRouteImport } from './routes/v3.index'
import { Route as V5SplatRouteImport } from './routes/v5.$'
import { Route as V4FlowStatesRouteImport } from './routes/v4.flow-states'
import { Route as V4ComponentsRouteImport } from './routes/v4.components'
import { Route as V3FlowStatesRouteImport } from './routes/v3.flow-states'
import { Route as V3ComponentsRouteImport } from './routes/v3.components'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ConnectionsTypeIdRouteImport } from './routes/connections.$typeId'
import { Route as V4ProjectsIndexRouteImport } from './routes/v4.projects.index'
import { Route as V4ProductsIndexRouteImport } from './routes/v4.products.index'
import { Route as V4LibraryIndexRouteImport } from './routes/v4.library.index'
import { Route as V4ConnectionsIndexRouteImport } from './routes/v4.connections.index'
import { Route as V3ProjectsIndexRouteImport } from './routes/v3.projects.index'
import { Route as V3ProductsIndexRouteImport } from './routes/v3.products.index'
import { Route as V3LibraryIndexRouteImport } from './routes/v3.library.index'
import { Route as V3ConnectionsIndexRouteImport } from './routes/v3.connections.index'
import { Route as V4ProjectsNewRouteImport } from './routes/v4.projects.new'
import { Route as V4ProjectsProjectIdRouteImport } from './routes/v4.projects.$projectId'
import { Route as V4ProductsProductIdRouteImport } from './routes/v4.products.$productId'
import { Route as V4ConnectionsTypeIdRouteImport } from './routes/v4.connections.$typeId'
import { Route as V3ProjectsNewRouteImport } from './routes/v3.projects.new'
import { Route as V3ProjectsProjectIdRouteImport } from './routes/v3.projects.$projectId'
import { Route as V3ProductsProductIdRouteImport } from './routes/v3.products.$productId'
import { Route as V3ConnectionsTypeIdRouteImport } from './routes/v3.connections.$typeId'
import { Route as ToolsToolIdWarningRouteImport } from './routes/tools.$toolId.warning'
import { Route as ToolsToolIdUploadRouteImport } from './routes/tools.$toolId.upload'
import { Route as ToolsToolIdSuccessRouteImport } from './routes/tools.$toolId.success'
import { Route as ToolsToolIdSourceRouteImport } from './routes/tools.$toolId.source'
import { Route as ToolsToolIdReviewRouteImport } from './routes/tools.$toolId.review'
import { Route as ToolsToolIdProcessingRouteImport } from './routes/tools.$toolId.processing'
import { Route as ToolsToolIdDegradedRouteImport } from './routes/tools.$toolId.degraded'
import { Route as ToolsToolIdBlockedRouteImport } from './routes/tools.$toolId.blocked'
import { Route as ToolsToolIdAboutRouteImport } from './routes/tools.$toolId.about'
import { Route as V4RunSemanticsGeneratorRecoveryRouteImport } from './routes/v4.run.semantics-generator.recovery'
import { Route as V4RunDashboardBuilderRecoveryRouteImport } from './routes/v4.run.dashboard-builder.recovery'
import { Route as V4RunCrossMinusRecoveryRouteImport } from './routes/v4.run.cross-minus.recovery'
import { Route as V4RunCampaignAnalysisRecoveryRouteImport } from './routes/v4.run.campaign-analysis.recovery'
import { Route as V4RunBdOptimizationRecoveryRouteImport } from './routes/v4.run.bd-optimization.recovery'
import { Route as V4RunProductIdStepRouteImport } from './routes/v4.run.$productId.$step'
import { Route as V3ToolsProductIdSourceRouteImport } from './routes/v3.tools.$productId.source'
import { Route as V3ToolsProductIdReviewRouteImport } from './routes/v3.tools.$productId.review'
import { Route as V3ToolsProductIdResultRouteImport } from './routes/v3.tools.$productId.result'
import { Route as V3ToolsProductIdProcessingRouteImport } from './routes/v3.tools.$productId.processing'

const V5Route = V5RouteImport.update({
  id: '/v5',
  path: '/v5',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowStatesRoute = FlowStatesRouteImport.update({
  id: '/flow-states',
  path: '/flow-states',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4IndexRoute = V4IndexRouteImport.update({
  id: '/v4/',
  path: '/v4/',
  getParentRoute: () => rootRouteImport,
} as any)
const V3IndexRoute = V3IndexRouteImport.update({
  id: '/v3/',
  path: '/v3/',
  getParentRoute: () => rootRouteImport,
} as any)
const V5SplatRoute = V5SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => V5Route,
} as any)
const V4FlowStatesRoute = V4FlowStatesRouteImport.update({
  id: '/v4/flow-states',
  path: '/v4/flow-states',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ComponentsRoute = V4ComponentsRouteImport.update({
  id: '/v4/components',
  path: '/v4/components',
  getParentRoute: () => rootRouteImport,
} as any)
const V3FlowStatesRoute = V3FlowStatesRouteImport.update({
  id: '/v3/flow-states',
  path: '/v3/flow-states',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ComponentsRoute = V3ComponentsRouteImport.update({
  id: '/v3/components',
  path: '/v3/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ConnectionsTypeIdRoute = ConnectionsTypeIdRouteImport.update({
  id: '/$typeId',
  path: '/$typeId',
  getParentRoute: () => ConnectionsRoute,
} as any)
const V4ProjectsIndexRoute = V4ProjectsIndexRouteImport.update({
  id: '/v4/projects/',
  path: '/v4/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ProductsIndexRoute = V4ProductsIndexRouteImport.update({
  id: '/v4/products/',
  path: '/v4/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4LibraryIndexRoute = V4LibraryIndexRouteImport.update({
  id: '/v4/library/',
  path: '/v4/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ConnectionsIndexRoute = V4ConnectionsIndexRouteImport.update({
  id: '/v4/connections/',
  path: '/v4/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ProjectsIndexRoute = V3ProjectsIndexRouteImport.update({
  id: '/v3/projects/',
  path: '/v3/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ProductsIndexRoute = V3ProductsIndexRouteImport.update({
  id: '/v3/products/',
  path: '/v3/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const V3LibraryIndexRoute = V3LibraryIndexRouteImport.update({
  id: '/v3/library/',
  path: '/v3/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ConnectionsIndexRoute = V3ConnectionsIndexRouteImport.update({
  id: '/v3/connections/',
  path: '/v3/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ProjectsNewRoute = V4ProjectsNewRouteImport.update({
  id: '/v4/projects/new',
  path: '/v4/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ProjectsProjectIdRoute = V4ProjectsProjectIdRouteImport.update({
  id: '/v4/projects/$projectId',
  path: '/v4/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ProductsProductIdRoute = V4ProductsProductIdRouteImport.update({
  id: '/v4/products/$productId',
  path: '/v4/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const V4ConnectionsTypeIdRoute = V4ConnectionsTypeIdRouteImport.update({
  id: '/v4/connections/$typeId',
  path: '/v4/connections/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ProjectsNewRoute = V3ProjectsNewRouteImport.update({
  id: '/v3/projects/new',
  path: '/v3/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ProjectsProjectIdRoute = V3ProjectsProjectIdRouteImport.update({
  id: '/v3/projects/$projectId',
  path: '/v3/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ProductsProductIdRoute = V3ProductsProductIdRouteImport.update({
  id: '/v3/products/$productId',
  path: '/v3/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ConnectionsTypeIdRoute = V3ConnectionsTypeIdRouteImport.update({
  id: '/v3/connections/$typeId',
  path: '/v3/connections/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdWarningRoute = ToolsToolIdWarningRouteImport.update({
  id: '/warning',
  path: '/warning',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdUploadRoute = ToolsToolIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdSuccessRoute = ToolsToolIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdSourceRoute = ToolsToolIdSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdReviewRoute = ToolsToolIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdProcessingRoute = ToolsToolIdProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdDegradedRoute = ToolsToolIdDegradedRouteImport.update({
  id: '/degraded',
  path: '/degraded',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdBlockedRoute = ToolsToolIdBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const ToolsToolIdAboutRoute = ToolsToolIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ToolsToolIdRoute,
} as any)
const V4RunSemanticsGeneratorRecoveryRoute =
  V4RunSemanticsGeneratorRecoveryRouteImport.update({
    id: '/v4/run/semantics-generator/recovery',
    path: '/v4/run/semantics-generator/recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const V4RunDashboardBuilderRecoveryRoute =
  V4RunDashboardBuilderRecoveryRouteImport.update({
    id: '/v4/run/dashboard-builder/recovery',
    path: '/v4/run/dashboard-builder/recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const V4RunCrossMinusRecoveryRoute = V4RunCrossMinusRecoveryRouteImport.update({
  id: '/v4/run/cross-minus/recovery',
  path: '/v4/run/cross-minus/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const V4RunCampaignAnalysisRecoveryRoute =
  V4RunCampaignAnalysisRecoveryRouteImport.update({
    id: '/v4/run/campaign-analysis/recovery',
    path: '/v4/run/campaign-analysis/recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const V4RunBdOptimizationRecoveryRoute =
  V4RunBdOptimizationRecoveryRouteImport.update({
    id: '/v4/run/bd-optimization/recovery',
    path: '/v4/run/bd-optimization/recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const V4RunProductIdStepRoute = V4RunProductIdStepRouteImport.update({
  id: '/v4/run/$productId/$step',
  path: '/v4/run/$productId/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ToolsProductIdSourceRoute = V3ToolsProductIdSourceRouteImport.update({
  id: '/v3/tools/$productId/source',
  path: '/v3/tools/$productId/source',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ToolsProductIdReviewRoute = V3ToolsProductIdReviewRouteImport.update({
  id: '/v3/tools/$productId/review',
  path: '/v3/tools/$productId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ToolsProductIdResultRoute = V3ToolsProductIdResultRouteImport.update({
  id: '/v3/tools/$productId/result',
  path: '/v3/tools/$productId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ToolsProductIdProcessingRoute =
  V3ToolsProductIdProcessingRouteImport.update({
    id: '/v3/tools/$productId/processing',
    path: '/v3/tools/$productId/processing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/flow-states': typeof FlowStatesRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/v5': typeof V5RouteWithChildren
  '/connections/$typeId': typeof ConnectionsTypeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tools/$toolId': typeof ToolsToolIdRouteWithChildren
  '/v3/components': typeof V3ComponentsRoute
  '/v3/flow-states': typeof V3FlowStatesRoute
  '/v4/components': typeof V4ComponentsRoute
  '/v4/flow-states': typeof V4FlowStatesRoute
  '/v5/$': typeof V5SplatRoute
  '/v3/': typeof V3IndexRoute
  '/v4/': typeof V4IndexRoute
  '/tools/$toolId/about': typeof ToolsToolIdAboutRoute
  '/tools/$toolId/blocked': typeof ToolsToolIdBlockedRoute
  '/tools/$toolId/degraded': typeof ToolsToolIdDegradedRoute
  '/tools/$toolId/processing': typeof ToolsToolIdProcessingRoute
  '/tools/$toolId/review': typeof ToolsToolIdReviewRoute
  '/tools/$toolId/source': typeof ToolsToolIdSourceRoute
  '/tools/$toolId/success': typeof ToolsToolIdSuccessRoute
  '/tools/$toolId/upload': typeof ToolsToolIdUploadRoute
  '/tools/$toolId/warning': typeof ToolsToolIdWarningRoute
  '/v3/connections/$typeId': typeof V3ConnectionsTypeIdRoute
  '/v3/products/$productId': typeof V3ProductsProductIdRoute
  '/v3/projects/$projectId': typeof V3ProjectsProjectIdRoute
  '/v3/projects/new': typeof V3ProjectsNewRoute
  '/v4/connections/$typeId': typeof V4ConnectionsTypeIdRoute
  '/v4/products/$productId': typeof V4ProductsProductIdRoute
  '/v4/projects/$projectId': typeof V4ProjectsProjectIdRoute
  '/v4/projects/new': typeof V4ProjectsNewRoute
  '/v3/connections/': typeof V3ConnectionsIndexRoute
  '/v3/library/': typeof V3LibraryIndexRoute
  '/v3/products/': typeof V3ProductsIndexRoute
  '/v3/projects/': typeof V3ProjectsIndexRoute
  '/v4/connections/': typeof V4ConnectionsIndexRoute
  '/v4/library/': typeof V4LibraryIndexRoute
  '/v4/products/': typeof V4ProductsIndexRoute
  '/v4/projects/': typeof V4ProjectsIndexRoute
  '/v3/tools/$productId/processing': typeof V3ToolsProductIdProcessingRoute
  '/v3/tools/$productId/result': typeof V3ToolsProductIdResultRoute
  '/v3/tools/$productId/review': typeof V3ToolsProductIdReviewRoute
  '/v3/tools/$productId/source': typeof V3ToolsProductIdSourceRoute
  '/v4/run/$productId/$step': typeof V4RunProductIdStepRoute
  '/v4/run/bd-optimization/recovery': typeof V4RunBdOptimizationRecoveryRoute
  '/v4/run/campaign-analysis/recovery': typeof V4RunCampaignAnalysisRecoveryRoute
  '/v4/run/cross-minus/recovery': typeof V4RunCrossMinusRecoveryRoute
  '/v4/run/dashboard-builder/recovery': typeof V4RunDashboardBuilderRecoveryRoute
  '/v4/run/semantics-generator/recovery': typeof V4RunSemanticsGeneratorRecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/flow-states': typeof FlowStatesRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/v5': typeof V5RouteWithChildren
  '/connections/$typeId': typeof ConnectionsTypeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tools/$toolId': typeof ToolsToolIdRouteWithChildren
  '/v3/components': typeof V3ComponentsRoute
  '/v3/flow-states': typeof V3FlowStatesRoute
  '/v4/components': typeof V4ComponentsRoute
  '/v4/flow-states': typeof V4FlowStatesRoute
  '/v5/$': typeof V5SplatRoute
  '/v3': typeof V3IndexRoute
  '/v4': typeof V4IndexRoute
  '/tools/$toolId/about': typeof ToolsToolIdAboutRoute
  '/tools/$toolId/blocked': typeof ToolsToolIdBlockedRoute
  '/tools/$toolId/degraded': typeof ToolsToolIdDegradedRoute
  '/tools/$toolId/processing': typeof ToolsToolIdProcessingRoute
  '/tools/$toolId/review': typeof ToolsToolIdReviewRoute
  '/tools/$toolId/source': typeof ToolsToolIdSourceRoute
  '/tools/$toolId/success': typeof ToolsToolIdSuccessRoute
  '/tools/$toolId/upload': typeof ToolsToolIdUploadRoute
  '/tools/$toolId/warning': typeof ToolsToolIdWarningRoute
  '/v3/connections/$typeId': typeof V3ConnectionsTypeIdRoute
  '/v3/products/$productId': typeof V3ProductsProductIdRoute
  '/v3/projects/$projectId': typeof V3ProjectsProjectIdRoute
  '/v3/projects/new': typeof V3ProjectsNewRoute
  '/v4/connections/$typeId': typeof V4ConnectionsTypeIdRoute
  '/v4/products/$productId': typeof V4ProductsProductIdRoute
  '/v4/projects/$projectId': typeof V4ProjectsProjectIdRoute
  '/v4/projects/new': typeof V4ProjectsNewRoute
  '/v3/connections': typeof V3ConnectionsIndexRoute
  '/v3/library': typeof V3LibraryIndexRoute
  '/v3/products': typeof V3ProductsIndexRoute
  '/v3/projects': typeof V3ProjectsIndexRoute
  '/v4/connections': typeof V4ConnectionsIndexRoute
  '/v4/library': typeof V4LibraryIndexRoute
  '/v4/products': typeof V4ProductsIndexRoute
  '/v4/projects': typeof V4ProjectsIndexRoute
  '/v3/tools/$productId/processing': typeof V3ToolsProductIdProcessingRoute
  '/v3/tools/$productId/result': typeof V3ToolsProductIdResultRoute
  '/v3/tools/$productId/review': typeof V3ToolsProductIdReviewRoute
  '/v3/tools/$productId/source': typeof V3ToolsProductIdSourceRoute
  '/v4/run/$productId/$step': typeof V4RunProductIdStepRoute
  '/v4/run/bd-optimization/recovery': typeof V4RunBdOptimizationRecoveryRoute
  '/v4/run/campaign-analysis/recovery': typeof V4RunCampaignAnalysisRecoveryRoute
  '/v4/run/cross-minus/recovery': typeof V4RunCrossMinusRecoveryRoute
  '/v4/run/dashboard-builder/recovery': typeof V4RunDashboardBuilderRecoveryRoute
  '/v4/run/semantics-generator/recovery': typeof V4RunSemanticsGeneratorRecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/connections': typeof ConnectionsRouteWithChildren
  '/flow-states': typeof FlowStatesRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/v5': typeof V5RouteWithChildren
  '/connections/$typeId': typeof ConnectionsTypeIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tools/$toolId': typeof ToolsToolIdRouteWithChildren
  '/v3/components': typeof V3ComponentsRoute
  '/v3/flow-states': typeof V3FlowStatesRoute
  '/v4/components': typeof V4ComponentsRoute
  '/v4/flow-states': typeof V4FlowStatesRoute
  '/v5/$': typeof V5SplatRoute
  '/v3/': typeof V3IndexRoute
  '/v4/': typeof V4IndexRoute
  '/tools/$toolId/about': typeof ToolsToolIdAboutRoute
  '/tools/$toolId/blocked': typeof ToolsToolIdBlockedRoute
  '/tools/$toolId/degraded': typeof ToolsToolIdDegradedRoute
  '/tools/$toolId/processing': typeof ToolsToolIdProcessingRoute
  '/tools/$toolId/review': typeof ToolsToolIdReviewRoute
  '/tools/$toolId/source': typeof ToolsToolIdSourceRoute
  '/tools/$toolId/success': typeof ToolsToolIdSuccessRoute
  '/tools/$toolId/upload': typeof ToolsToolIdUploadRoute
  '/tools/$toolId/warning': typeof ToolsToolIdWarningRoute
  '/v3/connections/$typeId': typeof V3ConnectionsTypeIdRoute
  '/v3/products/$productId': typeof V3ProductsProductIdRoute
  '/v3/projects/$projectId': typeof V3ProjectsProjectIdRoute
  '/v3/projects/new': typeof V3ProjectsNewRoute
  '/v4/connections/$typeId': typeof V4ConnectionsTypeIdRoute
  '/v4/products/$productId': typeof V4ProductsProductIdRoute
  '/v4/projects/$projectId': typeof V4ProjectsProjectIdRoute
  '/v4/projects/new': typeof V4ProjectsNewRoute
  '/v3/connections/': typeof V3ConnectionsIndexRoute
  '/v3/library/': typeof V3LibraryIndexRoute
  '/v3/products/': typeof V3ProductsIndexRoute
  '/v3/projects/': typeof V3ProjectsIndexRoute
  '/v4/connections/': typeof V4ConnectionsIndexRoute
  '/v4/library/': typeof V4LibraryIndexRoute
  '/v4/products/': typeof V4ProductsIndexRoute
  '/v4/projects/': typeof V4ProjectsIndexRoute
  '/v3/tools/$productId/processing': typeof V3ToolsProductIdProcessingRoute
  '/v3/tools/$productId/result': typeof V3ToolsProductIdResultRoute
  '/v3/tools/$productId/review': typeof V3ToolsProductIdReviewRoute
  '/v3/tools/$productId/source': typeof V3ToolsProductIdSourceRoute
  '/v4/run/$productId/$step': typeof V4RunProductIdStepRoute
  '/v4/run/bd-optimization/recovery': typeof V4RunBdOptimizationRecoveryRoute
  '/v4/run/campaign-analysis/recovery': typeof V4RunCampaignAnalysisRecoveryRoute
  '/v4/run/cross-minus/recovery': typeof V4RunCrossMinusRecoveryRoute
  '/v4/run/dashboard-builder/recovery': typeof V4RunDashboardBuilderRecoveryRoute
  '/v4/run/semantics-generator/recovery': typeof V4RunSemanticsGeneratorRecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/connections'
    | '/flow-states'
    | '/library'
    | '/projects'
    | '/v5'
    | '/connections/$typeId'
    | '/projects/$projectId'
    | '/tools/$toolId'
    | '/v3/components'
    | '/v3/flow-states'
    | '/v4/components'
    | '/v4/flow-states'
    | '/v5/$'
    | '/v3/'
    | '/v4/'
    | '/tools/$toolId/about'
    | '/tools/$toolId/blocked'
    | '/tools/$toolId/degraded'
    | '/tools/$toolId/processing'
    | '/tools/$toolId/review'
    | '/tools/$toolId/source'
    | '/tools/$toolId/success'
    | '/tools/$toolId/upload'
    | '/tools/$toolId/warning'
    | '/v3/connections/$typeId'
    | '/v3/products/$productId'
    | '/v3/projects/$projectId'
    | '/v3/projects/new'
    | '/v4/connections/$typeId'
    | '/v4/products/$productId'
    | '/v4/projects/$projectId'
    | '/v4/projects/new'
    | '/v3/connections/'
    | '/v3/library/'
    | '/v3/products/'
    | '/v3/projects/'
    | '/v4/connections/'
    | '/v4/library/'
    | '/v4/products/'
    | '/v4/projects/'
    | '/v3/tools/$productId/processing'
    | '/v3/tools/$productId/result'
    | '/v3/tools/$productId/review'
    | '/v3/tools/$productId/source'
    | '/v4/run/$productId/$step'
    | '/v4/run/bd-optimization/recovery'
    | '/v4/run/campaign-analysis/recovery'
    | '/v4/run/cross-minus/recovery'
    | '/v4/run/dashboard-builder/recovery'
    | '/v4/run/semantics-generator/recovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/connections'
    | '/flow-states'
    | '/library'
    | '/projects'
    | '/v5'
    | '/connections/$typeId'
    | '/projects/$projectId'
    | '/tools/$toolId'
    | '/v3/components'
    | '/v3/flow-states'
    | '/v4/components'
    | '/v4/flow-states'
    | '/v5/$'
    | '/v3'
    | '/v4'
    | '/tools/$toolId/about'
    | '/tools/$toolId/blocked'
    | '/tools/$toolId/degraded'
    | '/tools/$toolId/processing'
    | '/tools/$toolId/review'
    | '/tools/$toolId/source'
    | '/tools/$toolId/success'
    | '/tools/$toolId/upload'
    | '/tools/$toolId/warning'
    | '/v3/connections/$typeId'
    | '/v3/products/$productId'
    | '/v3/projects/$projectId'
    | '/v3/projects/new'
    | '/v4/connections/$typeId'
    | '/v4/products/$productId'
    | '/v4/projects/$projectId'
    | '/v4/projects/new'
    | '/v3/connections'
    | '/v3/library'
    | '/v3/products'
    | '/v3/projects'
    | '/v4/connections'
    | '/v4/library'
    | '/v4/products'
    | '/v4/projects'
    | '/v3/tools/$productId/processing'
    | '/v3/tools/$productId/result'
    | '/v3/tools/$productId/review'
    | '/v3/tools/$productId/source'
    | '/v4/run/$productId/$step'
    | '/v4/run/bd-optimization/recovery'
    | '/v4/run/campaign-analysis/recovery'
    | '/v4/run/cross-minus/recovery'
    | '/v4/run/dashboard-builder/recovery'
    | '/v4/run/semantics-generator/recovery'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/connections'
    | '/flow-states'
    | '/library'
    | '/projects'
    | '/v5'
    | '/connections/$typeId'
    | '/projects/$projectId'
    | '/tools/$toolId'
    | '/v3/components'
    | '/v3/flow-states'
    | '/v4/components'
    | '/v4/flow-states'
    | '/v5/$'
    | '/v3/'
    | '/v4/'
    | '/tools/$toolId/about'
    | '/tools/$toolId/blocked'
    | '/tools/$toolId/degraded'
    | '/tools/$toolId/processing'
    | '/tools/$toolId/review'
    | '/tools/$toolId/source'
    | '/tools/$toolId/success'
    | '/tools/$toolId/upload'
    | '/tools/$toolId/warning'
    | '/v3/connections/$typeId'
    | '/v3/products/$productId'
    | '/v3/projects/$projectId'
    | '/v3/projects/new'
    | '/v4/connections/$typeId'
    | '/v4/products/$productId'
    | '/v4/projects/$projectId'
    | '/v4/projects/new'
    | '/v3/connections/'
    | '/v3/library/'
    | '/v3/products/'
    | '/v3/projects/'
    | '/v4/connections/'
    | '/v4/library/'
    | '/v4/products/'
    | '/v4/projects/'
    | '/v3/tools/$productId/processing'
    | '/v3/tools/$productId/result'
    | '/v3/tools/$productId/review'
    | '/v3/tools/$productId/source'
    | '/v4/run/$productId/$step'
    | '/v4/run/bd-optimization/recovery'
    | '/v4/run/campaign-analysis/recovery'
    | '/v4/run/cross-minus/recovery'
    | '/v4/run/dashboard-builder/recovery'
    | '/v4/run/semantics-generator/recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  FlowStatesRoute: typeof FlowStatesRoute
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  V5Route: typeof V5RouteWithChildren
  ToolsToolIdRoute: typeof ToolsToolIdRouteWithChildren
  V3ComponentsRoute: typeof V3ComponentsRoute
  V3FlowStatesRoute: typeof V3FlowStatesRoute
  V4ComponentsRoute: typeof V4ComponentsRoute
  V4FlowStatesRoute: typeof V4FlowStatesRoute
  V3IndexRoute: typeof V3IndexRoute
  V4IndexRoute: typeof V4IndexRoute
  V3ConnectionsTypeIdRoute: typeof V3ConnectionsTypeIdRoute
  V3ProductsProductIdRoute: typeof V3ProductsProductIdRoute
  V3ProjectsProjectIdRoute: typeof V3ProjectsProjectIdRoute
  V3ProjectsNewRoute: typeof V3ProjectsNewRoute
  V4ConnectionsTypeIdRoute: typeof V4ConnectionsTypeIdRoute
  V4ProductsProductIdRoute: typeof V4ProductsProductIdRoute
  V4ProjectsProjectIdRoute: typeof V4ProjectsProjectIdRoute
  V4ProjectsNewRoute: typeof V4ProjectsNewRoute
  V3ConnectionsIndexRoute: typeof V3ConnectionsIndexRoute
  V3LibraryIndexRoute: typeof V3LibraryIndexRoute
  V3ProductsIndexRoute: typeof V3ProductsIndexRoute
  V3ProjectsIndexRoute: typeof V3ProjectsIndexRoute
  V4ConnectionsIndexRoute: typeof V4ConnectionsIndexRoute
  V4LibraryIndexRoute: typeof V4LibraryIndexRoute
  V4ProductsIndexRoute: typeof V4ProductsIndexRoute
  V4ProjectsIndexRoute: typeof V4ProjectsIndexRoute
  V3ToolsProductIdProcessingRoute: typeof V3ToolsProductIdProcessingRoute
  V3ToolsProductIdResultRoute: typeof V3ToolsProductIdResultRoute
  V3ToolsProductIdReviewRoute: typeof V3ToolsProductIdReviewRoute
  V3ToolsProductIdSourceRoute: typeof V3ToolsProductIdSourceRoute
  V4RunProductIdStepRoute: typeof V4RunProductIdStepRoute
  V4RunBdOptimizationRecoveryRoute: typeof V4RunBdOptimizationRecoveryRoute
  V4RunCampaignAnalysisRecoveryRoute: typeof V4RunCampaignAnalysisRecoveryRoute
  V4RunCrossMinusRecoveryRoute: typeof V4RunCrossMinusRecoveryRoute
  V4RunDashboardBuilderRecoveryRoute: typeof V4RunDashboardBuilderRecoveryRoute
  V4RunSemanticsGeneratorRecoveryRoute: typeof V4RunSemanticsGeneratorRecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v5': {
      id: '/v5'
      path: '/v5'
      fullPath: '/v5'
      preLoaderRoute: typeof V5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-states': {
      id: '/flow-states'
      path: '/flow-states'
      fullPath: '/flow-states'
      preLoaderRoute: typeof FlowStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/': {
      id: '/v4/'
      path: '/v4'
      fullPath: '/v4/'
      preLoaderRoute: typeof V4IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/': {
      id: '/v3/'
      path: '/v3'
      fullPath: '/v3/'
      preLoaderRoute: typeof V3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v5/$': {
      id: '/v5/$'
      path: '/$'
      fullPath: '/v5/$'
      preLoaderRoute: typeof V5SplatRouteImport
      parentRoute: typeof V5Route
    }
    '/v4/flow-states': {
      id: '/v4/flow-states'
      path: '/v4/flow-states'
      fullPath: '/v4/flow-states'
      preLoaderRoute: typeof V4FlowStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/components': {
      id: '/v4/components'
      path: '/v4/components'
      fullPath: '/v4/components'
      preLoaderRoute: typeof V4ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/flow-states': {
      id: '/v3/flow-states'
      path: '/v3/flow-states'
      fullPath: '/v3/flow-states'
      preLoaderRoute: typeof V3FlowStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/components': {
      id: '/v3/components'
      path: '/v3/components'
      fullPath: '/v3/components'
      preLoaderRoute: typeof V3ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/connections/$typeId': {
      id: '/connections/$typeId'
      path: '/$typeId'
      fullPath: '/connections/$typeId'
      preLoaderRoute: typeof ConnectionsTypeIdRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/v4/projects/': {
      id: '/v4/projects/'
      path: '/v4/projects'
      fullPath: '/v4/projects/'
      preLoaderRoute: typeof V4ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/products/': {
      id: '/v4/products/'
      path: '/v4/products'
      fullPath: '/v4/products/'
      preLoaderRoute: typeof V4ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/library/': {
      id: '/v4/library/'
      path: '/v4/library'
      fullPath: '/v4/library/'
      preLoaderRoute: typeof V4LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/connections/': {
      id: '/v4/connections/'
      path: '/v4/connections'
      fullPath: '/v4/connections/'
      preLoaderRoute: typeof V4ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/projects/': {
      id: '/v3/projects/'
      path: '/v3/projects'
      fullPath: '/v3/projects/'
      preLoaderRoute: typeof V3ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/products/': {
      id: '/v3/products/'
      path: '/v3/products'
      fullPath: '/v3/products/'
      preLoaderRoute: typeof V3ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/library/': {
      id: '/v3/library/'
      path: '/v3/library'
      fullPath: '/v3/library/'
      preLoaderRoute: typeof V3LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/connections/': {
      id: '/v3/connections/'
      path: '/v3/connections'
      fullPath: '/v3/connections/'
      preLoaderRoute: typeof V3ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/projects/new': {
      id: '/v4/projects/new'
      path: '/v4/projects/new'
      fullPath: '/v4/projects/new'
      preLoaderRoute: typeof V4ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/projects/$projectId': {
      id: '/v4/projects/$projectId'
      path: '/v4/projects/$projectId'
      fullPath: '/v4/projects/$projectId'
      preLoaderRoute: typeof V4ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/products/$productId': {
      id: '/v4/products/$productId'
      path: '/v4/products/$productId'
      fullPath: '/v4/products/$productId'
      preLoaderRoute: typeof V4ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/connections/$typeId': {
      id: '/v4/connections/$typeId'
      path: '/v4/connections/$typeId'
      fullPath: '/v4/connections/$typeId'
      preLoaderRoute: typeof V4ConnectionsTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/projects/new': {
      id: '/v3/projects/new'
      path: '/v3/projects/new'
      fullPath: '/v3/projects/new'
      preLoaderRoute: typeof V3ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/projects/$projectId': {
      id: '/v3/projects/$projectId'
      path: '/v3/projects/$projectId'
      fullPath: '/v3/projects/$projectId'
      preLoaderRoute: typeof V3ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/products/$productId': {
      id: '/v3/products/$productId'
      path: '/v3/products/$productId'
      fullPath: '/v3/products/$productId'
      preLoaderRoute: typeof V3ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/connections/$typeId': {
      id: '/v3/connections/$typeId'
      path: '/v3/connections/$typeId'
      fullPath: '/v3/connections/$typeId'
      preLoaderRoute: typeof V3ConnectionsTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId/warning': {
      id: '/tools/$toolId/warning'
      path: '/warning'
      fullPath: '/tools/$toolId/warning'
      preLoaderRoute: typeof ToolsToolIdWarningRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/upload': {
      id: '/tools/$toolId/upload'
      path: '/upload'
      fullPath: '/tools/$toolId/upload'
      preLoaderRoute: typeof ToolsToolIdUploadRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/success': {
      id: '/tools/$toolId/success'
      path: '/success'
      fullPath: '/tools/$toolId/success'
      preLoaderRoute: typeof ToolsToolIdSuccessRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/source': {
      id: '/tools/$toolId/source'
      path: '/source'
      fullPath: '/tools/$toolId/source'
      preLoaderRoute: typeof ToolsToolIdSourceRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/review': {
      id: '/tools/$toolId/review'
      path: '/review'
      fullPath: '/tools/$toolId/review'
      preLoaderRoute: typeof ToolsToolIdReviewRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/processing': {
      id: '/tools/$toolId/processing'
      path: '/processing'
      fullPath: '/tools/$toolId/processing'
      preLoaderRoute: typeof ToolsToolIdProcessingRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/degraded': {
      id: '/tools/$toolId/degraded'
      path: '/degraded'
      fullPath: '/tools/$toolId/degraded'
      preLoaderRoute: typeof ToolsToolIdDegradedRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/blocked': {
      id: '/tools/$toolId/blocked'
      path: '/blocked'
      fullPath: '/tools/$toolId/blocked'
      preLoaderRoute: typeof ToolsToolIdBlockedRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/tools/$toolId/about': {
      id: '/tools/$toolId/about'
      path: '/about'
      fullPath: '/tools/$toolId/about'
      preLoaderRoute: typeof ToolsToolIdAboutRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
    '/v4/run/semantics-generator/recovery': {
      id: '/v4/run/semantics-generator/recovery'
      path: '/v4/run/semantics-generator/recovery'
      fullPath: '/v4/run/semantics-generator/recovery'
      preLoaderRoute: typeof V4RunSemanticsGeneratorRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/run/dashboard-builder/recovery': {
      id: '/v4/run/dashboard-builder/recovery'
      path: '/v4/run/dashboard-builder/recovery'
      fullPath: '/v4/run/dashboard-builder/recovery'
      preLoaderRoute: typeof V4RunDashboardBuilderRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/run/cross-minus/recovery': {
      id: '/v4/run/cross-minus/recovery'
      path: '/v4/run/cross-minus/recovery'
      fullPath: '/v4/run/cross-minus/recovery'
      preLoaderRoute: typeof V4RunCrossMinusRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/run/campaign-analysis/recovery': {
      id: '/v4/run/campaign-analysis/recovery'
      path: '/v4/run/campaign-analysis/recovery'
      fullPath: '/v4/run/campaign-analysis/recovery'
      preLoaderRoute: typeof V4RunCampaignAnalysisRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/run/bd-optimization/recovery': {
      id: '/v4/run/bd-optimization/recovery'
      path: '/v4/run/bd-optimization/recovery'
      fullPath: '/v4/run/bd-optimization/recovery'
      preLoaderRoute: typeof V4RunBdOptimizationRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4/run/$productId/$step': {
      id: '/v4/run/$productId/$step'
      path: '/v4/run/$productId/$step'
      fullPath: '/v4/run/$productId/$step'
      preLoaderRoute: typeof V4RunProductIdStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/tools/$productId/source': {
      id: '/v3/tools/$productId/source'
      path: '/v3/tools/$productId/source'
      fullPath: '/v3/tools/$productId/source'
      preLoaderRoute: typeof V3ToolsProductIdSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/tools/$productId/review': {
      id: '/v3/tools/$productId/review'
      path: '/v3/tools/$productId/review'
      fullPath: '/v3/tools/$productId/review'
      preLoaderRoute: typeof V3ToolsProductIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/tools/$productId/result': {
      id: '/v3/tools/$productId/result'
      path: '/v3/tools/$productId/result'
      fullPath: '/v3/tools/$productId/result'
      preLoaderRoute: typeof V3ToolsProductIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/tools/$productId/processing': {
      id: '/v3/tools/$productId/processing'
      path: '/v3/tools/$productId/processing'
      fullPath: '/v3/tools/$productId/processing'
      preLoaderRoute: typeof V3ToolsProductIdProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectionsRouteChildren {
  ConnectionsTypeIdRoute: typeof ConnectionsTypeIdRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsTypeIdRoute: ConnectionsTypeIdRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface V5RouteChildren {
  V5SplatRoute: typeof V5SplatRoute
}

const V5RouteChildren: V5RouteChildren = {
  V5SplatRoute: V5SplatRoute,
}

const V5RouteWithChildren = V5Route._addFileChildren(V5RouteChildren)

interface ToolsToolIdRouteChildren {
  ToolsToolIdAboutRoute: typeof ToolsToolIdAboutRoute
  ToolsToolIdBlockedRoute: typeof ToolsToolIdBlockedRoute
  ToolsToolIdDegradedRoute: typeof ToolsToolIdDegradedRoute
  ToolsToolIdProcessingRoute: typeof ToolsToolIdProcessingRoute
  ToolsToolIdReviewRoute: typeof ToolsToolIdReviewRoute
  ToolsToolIdSourceRoute: typeof ToolsToolIdSourceRoute
  ToolsToolIdSuccessRoute: typeof ToolsToolIdSuccessRoute
  ToolsToolIdUploadRoute: typeof ToolsToolIdUploadRoute
  ToolsToolIdWarningRoute: typeof ToolsToolIdWarningRoute
}

const ToolsToolIdRouteChildren: ToolsToolIdRouteChildren = {
  ToolsToolIdAboutRoute: ToolsToolIdAboutRoute,
  ToolsToolIdBlockedRoute: ToolsToolIdBlockedRoute,
  ToolsToolIdDegradedRoute: ToolsToolIdDegradedRoute,
  ToolsToolIdProcessingRoute: ToolsToolIdProcessingRoute,
  ToolsToolIdReviewRoute: ToolsToolIdReviewRoute,
  ToolsToolIdSourceRoute: ToolsToolIdSourceRoute,
  ToolsToolIdSuccessRoute: ToolsToolIdSuccessRoute,
  ToolsToolIdUploadRoute: ToolsToolIdUploadRoute,
  ToolsToolIdWarningRoute: ToolsToolIdWarningRoute,
}

const ToolsToolIdRouteWithChildren = ToolsToolIdRoute._addFileChildren(
  ToolsToolIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  FlowStatesRoute: FlowStatesRoute,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  V5Route: V5RouteWithChildren,
  ToolsToolIdRoute: ToolsToolIdRouteWithChildren,
  V3ComponentsRoute: V3ComponentsRoute,
  V3FlowStatesRoute: V3FlowStatesRoute,
  V4ComponentsRoute: V4ComponentsRoute,
  V4FlowStatesRoute: V4FlowStatesRoute,
  V3IndexRoute: V3IndexRoute,
  V4IndexRoute: V4IndexRoute,
  V3ConnectionsTypeIdRoute: V3ConnectionsTypeIdRoute,
  V3ProductsProductIdRoute: V3ProductsProductIdRoute,
  V3ProjectsProjectIdRoute: V3ProjectsProjectIdRoute,
  V3ProjectsNewRoute: V3ProjectsNewRoute,
  V4ConnectionsTypeIdRoute: V4ConnectionsTypeIdRoute,
  V4ProductsProductIdRoute: V4ProductsProductIdRoute,
  V4ProjectsProjectIdRoute: V4ProjectsProjectIdRoute,
  V4ProjectsNewRoute: V4ProjectsNewRoute,
  V3ConnectionsIndexRoute: V3ConnectionsIndexRoute,
  V3LibraryIndexRoute: V3LibraryIndexRoute,
  V3ProductsIndexRoute: V3ProductsIndexRoute,
  V3ProjectsIndexRoute: V3ProjectsIndexRoute,
  V4ConnectionsIndexRoute: V4ConnectionsIndexRoute,
  V4LibraryIndexRoute: V4LibraryIndexRoute,
  V4ProductsIndexRoute: V4ProductsIndexRoute,
  V4ProjectsIndexRoute: V4ProjectsIndexRoute,
  V3ToolsProductIdProcessingRoute: V3ToolsProductIdProcessingRoute,
  V3ToolsProductIdResultRoute: V3ToolsProductIdResultRoute,
  V3ToolsProductIdReviewRoute: V3ToolsProductIdReviewRoute,
  V3ToolsProductIdSourceRoute: V3ToolsProductIdSourceRoute,
  V4RunProductIdStepRoute: V4RunProductIdStepRoute,
  V4RunBdOptimizationRecoveryRoute: V4RunBdOptimizationRecoveryRoute,
  V4RunCampaignAnalysisRecoveryRoute: V4RunCampaignAnalysisRecoveryRoute,
  V4RunCrossMinusRecoveryRoute: V4RunCrossMinusRecoveryRoute,
  V4RunDashboardBuilderRecoveryRoute: V4RunDashboardBuilderRecoveryRoute,
  V4RunSemanticsGeneratorRecoveryRoute: V4RunSemanticsGeneratorRecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
